package testco.kotlin.data.exception

/**
 * Created by Concaro on 8/21/2017.
 */
class MapperException : Exception {

    constructor() : super()
    constructor(cause: Throwable?) : super(cause)
}